In [1]:
import numpy as np 

## DataTypes & Attributes

In [2]:
# Numpy's main datatype os ndarray
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [5]:
a2 = np.array([[1,2,3.3],
               [4,5,6.5]])

a3 = np.array([[[1,2,3],
               [4,5,6],
               [7,8,9]],
              [[10,11,12],
              [13,14,15],
              [16,17,18]]])

In [6]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [7]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [9]:
a1.shape

(3,)

In [10]:
a2.shape

(2, 3)

In [11]:
a3.shape

(2, 3, 3)

In [12]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [13]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [14]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [15]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [17]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [16]:
# Create a DataFrame from a NumPy array
import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

## 2. Creating arrays

In [18]:
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

In [20]:
sample_array.dtype

dtype('int64')

In [21]:
ones = np.ones((2,3))

In [22]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [23]:
ones.dtype

dtype('float64')

In [24]:
type(ones)

numpy.ndarray

In [25]:
zeros = np.zeros((2,3))

In [26]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [27]:
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [28]:
random_array = np.random.randint(0, 10, size = (3, 5))
random_array

array([[0, 4, 6, 0, 5],
       [9, 9, 9, 9, 9],
       [2, 1, 0, 5, 8]])

In [29]:
random_array.size

15

In [30]:
random_array.shape

(3, 5)

In [31]:
random_array_2 = np.random.random((5,3))
random_array_2

array([[0.49771326, 0.7946255 , 0.33221683],
       [0.66235029, 0.56711705, 0.83613878],
       [0.99737297, 0.29778268, 0.95233537],
       [0.38698115, 0.21168846, 0.51507615],
       [0.49495284, 0.66372896, 0.90186732]])

In [33]:
random_array_2.shape

(5, 3)

In [35]:
random_array_3 = np.random.rand(5, 3)
random_array_3

array([[0.00762791, 0.48366299, 0.06541885],
       [0.16381865, 0.17788361, 0.13841835],
       [0.67036754, 0.37977917, 0.1907899 ],
       [0.61838047, 0.88726647, 0.31631007],
       [0.20435973, 0.00704056, 0.12186482]])

In [42]:
# Pseudo-random numbers
np.random.seed(seed=999)
random_array_4 = np.random.randint(10, size=(5, 3))
random_array_4

array([[0, 5, 1],
       [8, 1, 9],
       [3, 0, 5],
       [8, 8, 0],
       [5, 2, 5]])

In [44]:
npm.random.seed(7)
random_array_5 = np.random.random((5,3))
random_array_5

NameError: name 'npm' is not defined

In [39]:
random_array_4.shape

(5, 3)