In [1]:
import numpy as np 

## DataTypes & Attributes

In [2]:
# Numpy's main datatype os ndarray
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [5]:
a2 = np.array([[1,2,3.3],
               [4,5,6.5]])

a3 = np.array([[[1,2,3],
               [4,5,6],
               [7,8,9]],
              [[10,11,12],
              [13,14,15],
              [16,17,18]]])

In [6]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [7]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [9]:
a1.shape

(3,)

In [10]:
a2.shape

(2, 3)

In [11]:
a3.shape

(2, 3, 3)

In [12]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [13]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [14]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [15]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [17]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [16]:
# Create a DataFrame from a NumPy array
import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

## 2. Creating arrays

In [18]:
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

In [20]:
sample_array.dtype

dtype('int64')

In [21]:
ones = np.ones((2,3))

In [22]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [23]:
ones.dtype

dtype('float64')

In [24]:
type(ones)

numpy.ndarray

In [25]:
zeros = np.zeros((2,3))

In [26]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [27]:
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [28]:
random_array = np.random.randint(0, 10, size = (3, 5))
random_array

array([[0, 4, 6, 0, 5],
       [9, 9, 9, 9, 9],
       [2, 1, 0, 5, 8]])

In [29]:
random_array.size

15

In [30]:
random_array.shape

(3, 5)

In [31]:
random_array_2 = np.random.random((5,3))
random_array_2

array([[0.49771326, 0.7946255 , 0.33221683],
       [0.66235029, 0.56711705, 0.83613878],
       [0.99737297, 0.29778268, 0.95233537],
       [0.38698115, 0.21168846, 0.51507615],
       [0.49495284, 0.66372896, 0.90186732]])

In [33]:
random_array_2.shape

(5, 3)

In [35]:
random_array_3 = np.random.rand(5, 3)
random_array_3

array([[0.00762791, 0.48366299, 0.06541885],
       [0.16381865, 0.17788361, 0.13841835],
       [0.67036754, 0.37977917, 0.1907899 ],
       [0.61838047, 0.88726647, 0.31631007],
       [0.20435973, 0.00704056, 0.12186482]])

In [47]:
# Pseudo-random numbers
np.random.seed(seed=99999)
random_array_4 = np.random.randint(10, size=(5, 3))
random_array_4

array([[0, 3, 1],
       [8, 1, 3],
       [8, 5, 6],
       [0, 6, 0],
       [4, 0, 9]])

In [45]:
np.random.seed(7)
random_array_5 = np.random.random((5,3))
random_array_5

array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587],
       [0.50112046, 0.07205113, 0.26843898],
       [0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 ]])

In [46]:
random_array_5 = np.random.random((5,3))
random_array_5

array([[0.90959353, 0.21338535, 0.45212396],
       [0.93120602, 0.02489923, 0.60054892],
       [0.9501295 , 0.23030288, 0.54848992],
       [0.90912837, 0.13316945, 0.52341258],
       [0.75040986, 0.66901324, 0.46775286]])

In [48]:
random_array_4

array([[0, 3, 1],
       [8, 1, 3],
       [8, 5, 6],
       [0, 6, 0],
       [4, 0, 9]])

### 3. Viewing arrays and matrices

In [49]:
np.unique(random_array_4)

array([0, 1, 3, 4, 5, 6, 8, 9])

In [50]:
a1

array([1, 2, 3])

In [51]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [52]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [53]:
a1[0]

1

In [54]:
a2[0]

array([1. , 2. , 3.3])

In [55]:
a3.shape

(2, 3, 3)

In [65]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [57]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [58]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [59]:
a2[1]

array([4. , 5. , 6.5])

In [60]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [63]:
a3[:2, :2, :2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [67]:
a4 = np.random.randint(10, size = (2,3,4,5))
a4

array([[[[7, 9, 3, 6, 0],
         [1, 6, 9, 4, 6],
         [0, 3, 3, 5, 3],
         [4, 3, 9, 7, 1]],

        [[5, 8, 8, 1, 3],
         [8, 8, 0, 3, 9],
         [2, 1, 3, 5, 6],
         [0, 4, 2, 3, 0]],

        [[4, 1, 3, 4, 4],
         [7, 2, 1, 3, 4],
         [0, 5, 9, 6, 3],
         [9, 0, 5, 0, 6]]],


       [[[5, 6, 2, 4, 2],
         [3, 5, 2, 3, 5],
         [8, 2, 0, 1, 8],
         [9, 8, 5, 2, 9]],

        [[5, 6, 8, 3, 7],
         [0, 6, 6, 0, 5],
         [4, 8, 5, 8, 1],
         [9, 3, 1, 9, 7]],

        [[7, 4, 4, 1, 4],
         [0, 0, 7, 6, 9],
         [6, 2, 4, 0, 3],
         [8, 6, 2, 1, 2]]]])

In [68]:
a4.shape, a4.ndim

((2, 3, 4, 5), 4)

In [71]:
# Get the first 4 numbers of the inner most arrays
a4[:, :, :, :4]

array([[[[7, 9, 3, 6],
         [1, 6, 9, 4],
         [0, 3, 3, 5],
         [4, 3, 9, 7]],

        [[5, 8, 8, 1],
         [8, 8, 0, 3],
         [2, 1, 3, 5],
         [0, 4, 2, 3]],

        [[4, 1, 3, 4],
         [7, 2, 1, 3],
         [0, 5, 9, 6],
         [9, 0, 5, 0]]],


       [[[5, 6, 2, 4],
         [3, 5, 2, 3],
         [8, 2, 0, 1],
         [9, 8, 5, 2]],

        [[5, 6, 8, 3],
         [0, 6, 6, 0],
         [4, 8, 5, 8],
         [9, 3, 1, 9]],

        [[7, 4, 4, 1],
         [0, 0, 7, 6],
         [6, 2, 4, 0],
         [8, 6, 2, 1]]]])

## 4. Manipulating & comparing arrays

### Arithmetic 

In [72]:
a1 

array([1, 2, 3])

In [74]:
ones = np.ones(3)
ones

array([1., 1., 1.])

In [75]:
a1 + ones

array([2., 3., 4.])

In [76]:
a1 - ones

array([0., 1., 2.])

In [80]:
a1 * ones

array([1., 2., 3.])

In [78]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [79]:
a1 * a2

array([[ 1. ,  4. ,  9.9],
       [ 4. , 10. , 19.5]])

In [81]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [82]:
# How can you reshape a2 to be compatible with a3?
# Search: "How to reshape numpy array"
a2 * a3

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

In [83]:
a1 / ones 

array([1., 2., 3.])

In [85]:
a2 / a1

array([[1.        , 1.        , 1.1       ],
       [4.        , 2.5       , 2.16666667]])

In [84]:
# Floor division removes the decimals (rounds down)
a2 // a1

array([[1., 1., 1.],
       [4., 2., 2.]])

In [86]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [87]:
a2 ** 2

array([[ 1.  ,  4.  , 10.89],
       [16.  , 25.  , 42.25]])

In [88]:
np.square(a2)

array([[ 1.  ,  4.  , 10.89],
       [16.  , 25.  , 42.25]])

In [89]:
np.add(a1, ones)

array([2., 3., 4.])

In [90]:
a1

array([1, 2, 3])

In [91]:
a1 % 2 

array([1, 0, 1])

In [92]:
a2 % 2 

array([[1. , 0. , 1.3],
       [0. , 1. , 0.5]])

In [93]:
np.exp(a1)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [94]:
np.log(a1)

array([0.        , 0.69314718, 1.09861229])